In [8]:
%matplotlib inline

import cv2
import numpy as np
from matplotlib import pyplot as plt

In [18]:
img = cv2.imread("pics/cameraman.bmp",cv2.IMREAD_COLOR)

Every video breaks down into frames. Each frame, like an image, then breaks down into pixels stored in rows and columns within the frame/picture. Each pixel has a coordinate location, and each pixel is comprised of color values. Let's work out some examples of accessing various bits of these principles.

In [19]:
px = img[55,55]

print(px)

[180 180 180]


In [20]:
#region of image
roi = img[100:150,100:150]

print(roi)

[[[  9   9   9]
  [ 11  11  11]
  [ 13  13  13]
  ..., 
  [ 18  18  18]
  [ 20  20  20]
  [ 19  19  19]]

 [[ 12  12  12]
  [ 12  12  12]
  [ 12  12  12]
  ..., 
  [ 25  25  25]
  [ 17  17  17]
  [ 16  16  16]]

 [[ 13  13  13]
  [ 12  12  12]
  [ 12  12  12]
  ..., 
  [ 23  23  23]
  [ 23  23  23]
  [ 18  18  18]]

 ..., 
 [[ 15  15  15]
  [ 14  14  14]
  [ 14  14  14]
  ..., 
  [ 92  92  92]
  [113 113 113]
  [127 127 127]]

 [[ 14  14  14]
  [ 15  15  15]
  [ 14  14  14]
  ..., 
  [108 108 108]
  [126 126 126]
  [135 135 135]]

 [[ 15  15  15]
  [ 15  15  15]
  [ 16  16  16]
  ..., 
  [113 113 113]
  [130 130 130]
  [143 143 143]]]


In [21]:
img[100:150,100:150] = [255,255,255]

In [22]:
white_rectangle = img[100:150,100:150]

img[0:50,0:50] = white_rectangle

In [23]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()